### ISSUE TITLE
segfault on giving a file instead of a directory as arg

### ISSUE THREAD

**Issue by grimm26** [terraform-docs/terraform-docs#325] opened 2020-09-24 17:43 UTC
**Describe the bug**

on 0.10.0 if I give a file instead of a directory as the arg, terraform-docs segfaults.  It used to give an error message.

**To Reproduce**

1. Give a file instead of a directory as the path argument.

```
12:40:42 ❯ terraform-docs markdown ./main.tf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fdbe6]

goroutine 1 [running]:
github.com/terraform-docs/terraform-docs/internal/cli.(*cfgreader).exist(0xc0001701c0, 0xc0001701c0, 0x2, 0xc00016a980)
        /private/tmp/terraform-docs-20200921-68242-fhrnj8/terraform-docs-0.10.0/internal/cli/reader.go:22 +0xc6
github.com/terraform-docs/terraform-docs/internal/cli.PreRunEFunc.func1(0xc00015f8c0, 0xc0001e2190, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/terraform-docs-20200921-68242-fhrnj8/terraform-docs-0.10.0/internal/cli/run.go:46 +0x1b9
github.com/spf13/cobra.(*Command).execute(0xc00015f8c0, 0xc0001e2170, 0x1, 0x1, 0xc00015f8c0, 0xc0001e2170)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:831 +0x530
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015eb00, 0x1044337, 0x17630e0, 0xc000116030)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/terraform-docs/terraform-docs/cmd.Execute(0x1434440, 0xc0000260b8)
        /private/tmp/terraform-docs-20200921-68242-fhrnj8/terraform-docs-0.10.0/cmd/root.go:24 +0x2b
main.main()
        /private/tmp/terraform-docs-20200921-68242-fhrnj8/terraform-docs-0.10.0/main.go:10 +0x25
```

**Expected behavior**

`Error: Failed to read module directory: Module directory ./main.tf does not exist or cannot be read.`

**Version information:**

- terraform-docs version (use `terraform-docs --version`): `terraform-docs version v0.0.0- v0.10.0 darwin/amd64 BuildDate: 2020-09-21T21:42:24+0100`
- Go version (if you manually built. use `go version`):
- OS (e.g. Windows, MacOS): MacOS

**Additional context**

**Comment by khos2ow** [comment] 2020-09-25 15:28
This is actually duplicate of #297, I'll close this in favor of that.

**Closed by khos2ow** 2020-09-25 15:28 UTC
Labels: bug
