### ISSUE TITLE
Terraform 0.15.0 configuration_aliases trips up terraform-docs

### ISSUE THREAD

**Issue by kneufeld-pbp** [terraform-docs/terraform-docs#477] opened 2021-04-22 06:33 UTC
### Describe the bug
`terraform-docs` throws  **_Error: Variables not allowed: Variables may not be used here._**  when `configuration_aliases` is set with unquoted *alias* as required by Terraform 0.15.0 

### How can we reproduce it?
This will cause the error:
 ```
terraform {
  required_version = "~> 0.15.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.10.0"
      configuration_aliases = [
        aws.us_east
      ]
    }
  }
}
```

`terraform-docs` to run without error by terraform 0.15.0 validate will fail
```
terraform {
  required_version = "~> 0.15.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.10.0"
      configuration_aliases = [
        "aws.us_east"
      ]
    }
  }
}
```

### Environment information
terraform version: `v0.15.0`
terraform-docs: `v0.12.1`
os: macos `10.15.7`

**Comment by khos2ow** [comment] 2021-04-22 17:09
duplicate of #473.

**Closed by khos2ow** 2021-04-22 17:09 UTC
Labels: bug
