### ISSUE TITLE
Feature : generate a module usage example from code 

### ISSUE THREAD

**Issue by Ameausoone** [terraform-docs/terraform-docs#378] opened 2021-02-04 10:14 UTC
### What problem are you facing?

I'm using terraform-docs (awesome project BTW), I'm using it to auto document modules. But I find no way, to build automatically an example of module usage . 

### How could terraform-docs help solve your problem?

I would like to build this automatically from code =>

```hcl-terraform
module "vm-name-to-override" {
  source              = "git@github.com:orga/terraform.git//modules/compute-instance"
  project             = "my-project-id"
  region              = "europe-west1-b"
  labels               = { env: "dev"}

}
``` 

and could inject it in README.md.

**Comment by khos2ow** [comment] 2021-02-04 19:06
Looks like a duplicate of #313, although the intention of here is to generate from "code" and the other one from `examples` folder. Maybe we can consolidate both.

**Comment by tarunngc** [comment] 2021-04-08 19:35
@khos2ow I would be interested in potentially implementing this capability. Thoughts?

**Comment by khos2ow** [comment] 2021-05-11 22:31
@tarunngc apology for the delay, I just saw your message. I was working on #486 and it's almost finished.

You can pick this up then and we can introduce a new template function, called `file` or `embed` or etc, so eventually one can add any random file as part of the generated output.

```
$ tree
.
├── examples
│   ├── example-1
│   │   ├── main.tf
│   └── example-2
│       └── main.tf
├── ...
├── main.tf
├── variables.tf
├── ...
└── .terraform-docs.yml
```

    # .terraform-docs.yml
    ...
    content: |-
      {{ .Header }}
    
      ## Example
    
      ```hcl
      {{ file "example-1/main.tf" }}
      ```
    
      {{ .Inputs }}
    
      {{ .Outputs }}

What do you think?

**Closed** 2021-05-13 17:08 UTC
Labels: feature request
