### ISSUE TITLE
Add documentation output for all consumed module references

### ISSUE THREAD

**Issue by aaronsteers** [terraform-docs/terraform-docs#365] opened 2021-01-04 20:34 UTC
_**Note:** This was originally tracked in a combined issue with another feature in #287. Splitting this out into a separate issue for tracking purposes so the other feature (#347) can cleanly be closed._

----------------------

## Is your feature request related to a problem? Please describe.

I want to expose module dependencies in a similar way as declared providers are documented.

## Describe the solution you'd like

A new section to be created to document module dependencies for the targeted module:

Something like...

```
## External modules referenced:

- `tableau-server`
  - local alias: `my_tableau_server`
  - source: https://github.com/slalom-ggp/dataops-infra/tree/main/catalog/aws/tableau-server
  - version reference: `master`
- ...
```

## Additional context

As we invest more in larger modules, we want users to be able to better understand how those modules are composed, and what interdependencies exist between modules.

--------------------------

_Split per request from @khos2ow in https://github.com/terraform-docs/terraform-docs/issues/287#issuecomment-754185627_

**Comment by khos2ow** [comment] 2021-01-30 01:45
This seems to be a duplicate of #255, closing this in favor of the original one. @aaronsteers please feel free to comment your feedback on the other ticket or existing PR.

**Closed by khos2ow** 2021-01-30 01:45 UTC
Labels: feature request, section/module
