### ISSUE TITLE
Allow to tag a section for generating the documentation

### ISSUE THREAD

**Issue by yordis** [terraform-docs/terraform-docs#286] opened 2020-07-05 02:53 UTC
**Is your feature request related to a problem? Please describe.**

I am using `terraform-docs markdown table --sort-by-required . > README.md` to generate the documentation right now, the problem with this approach is that I lose the content of the `README.md` file (if I append the content, then I must deal with removing content).
#

**Describe the solution you'd like**

Add `--output-file` option, for example:

```shell
terraform-docs markdown table --sort-by-required --output-file ./README.md
```

The `--output-file` is the value of the file that the CLI will try to replace the content of the following tag with the output of the command:

```text
`<!-- terraformdoc --><!-- terraformdocstop -->`
```

Example `README.md` file:

```
# My Module Name

## Example Usage
.... more content

<!-- terraformdoc -->
 ..... replace the content here ...
<!-- terraformdocstop -->

... more content
```

**Describe alternatives you've considered**

Manual work.

**Comment by khos2ow** [comment] 2020-07-06 19:47
This is a duplicate of #99. As discussed on that ticket `terraform-docs` follows Unix Philosophy, do one thing and do it well, otherwise things will get out of scope of _terraform-docs_ as a tool. You can incorporate [antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform) in your workflows, or create a `Makefile` target as follow for example:

```makefile
.PHONY: document
document: START_TOKEN := <!-- terraform-docs starts -->
document: END_TOKEN   := <!-- terraform-docs ends -->
document: ## Generate document in README
	@ if [ "`grep "terraform-docs starts" README.md | wc -l`" = 0 ]; then \
		echo "${START_TOKEN}\n" >> README.md ; \
		terraform-docs --sort-by-required markdown table ./ >> README.md ; \
		echo "${END_TOKEN}" >> README.md ; \
	else \
		terraform-docs --sort-by-required markdown table ./ > "./tmp_doc" ; \
		perl -i -ne 'if (/${START_TOKEN}/../${END_TOKEN}/) { print $$_ if /${START_TOKEN}/; print "\nI_WANT_TO_BE_REPLACED\n$$_" if /${END_TOKEN}/;} else { print $$_ }' README.md ; \
		perl -i -e 'open(F, "'"./tmp_doc"'"); $$f = join "", <F>; while(<>){if (/I_WANT_TO_BE_REPLACED/) {print $$f} else {print $$_};}' README.md ; \
		rm -f "./tmp_doc" ; \
	fi
```

**Comment by michelzanini** [comment] 2020-07-25 18:04
@khos2ow Understand your point here, but is it not the case that almost every person that uses `terraform-docs` will want to achieve this? In that case, would it not be much better if this was supported directly from `terraform-docs`?

**Comment by khos2ow** [comment] 2021-03-09 20:12
I've just opened #425 which will address this! Please take a look and give your feedbacks.

**Closed** 2021-03-09 21:42 UTC
Labels: cmd/new flag, document needed, feature request
