### ISSUE TITLE
`configuration_aliases` in required_providers block doesn't supported

### ISSUE THREAD

**Issue by ndolya** [terraform-docs/terraform-docs#480] opened 2021-04-26 17:59 UTC
### Describe the bug

Can not generate markdown output if `configuration_aliases` is in terraform required_providers block.

### How can we reproduce it?

add the following:
```tf
terraform {
  required_providers {
    aws = {
      source                = "hashicorp/aws"
      version               = "~> 3.27"
      configuration_aliases = [aws.test]
    }
  }
  required_version = ">= 0.13"
}

```

### Environment information
- terraform-docs version 0.12.1
- MacOS
- terraform version 0.15.0

**Comment by khos2ow** [comment] 2021-04-26 23:55
duplicate of #473

**Closed by khos2ow** 2021-04-26 23:55 UTC
Labels: bug
