### ISSUE TITLE
Resources section generates bad links

### ISSUE THREAD

**Issue by kral2** [terraform-docs/terraform-docs#407] opened 2021-02-25 04:14 UTC
### Describe the bug

It seems the version constraints dictates which version of the doc is linked. But when having a constraint like `>= 3.27`for example, the minimum version is used instead of the latest.

Resources section generates bad links:
- I would expect to have a link to the current version of the documentation for the particular provider
- links are generated with a url that targets version 3.27 of this particular provider, and HTTP404 is returned.

### How can we reproduce it?

Example of a `resource` block generated with this command: `> terraform-docs markdown . > doc.md`

```
## Requirements

| Name | Version |
|------|---------|
| terraform | >= 0.12 |
| oci | >= 3.27 |

## Providers

| Name | Version |
|------|---------|
| oci | >= 3.27 |

## Modules

No Modules.
## Resources

| Name |
|------|
| [oci_core_instance_credentials](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/data-sources/core_instance_credentials) |
| [oci_core_instance](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/resources/core_instance) |
| [oci_core_shapes](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/data-sources/core_shapes) |
| [oci_core_subnet](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/data-sources/core_subnet) |
| [oci_core_volume_attachment](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/resources/core_volume_attachment) |
| [oci_core_volume](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/resources/core_volume) |
| [oci_identity_availability_domains](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/data-sources/identity_availability_domains) |
```

if the url was generated with `/latest/` instead of `/3.27/` the link would be working.
- Example of a generated bad link: [oci_core_instance_credentials](https://registry.terraform.io/providers/hashicorp/oci/3.27/docs/data-sources/core_instance_credentials)
- Example of a generated link that would work: [oci_core_instance_credentials](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/core_instance_credentials)

### Environment information

terraform-docs version v0.11.1 darwin/amd64 BuildDate: 2021-02-18T20:28:57+0000

**Comment by khos2ow** [comment] 2021-02-25 16:28
This is duplicate of #390 and fixed in `v0.11.2`.

**Closed** 2021-02-26 20:48 UTC
Labels: bug
